### PR TITLE
Refactor string processing

### LINKED ISSUE #6: regexp tests only one timestamp
The org rexexp you are using, org-ts-regexp-both,  only tests a timestamp. You should be using org-tr-regexp or org-tr-regexp-both. Even then you are not testing the "CLOCK:" string in front of the range.

As response to an Emacs StackExchange question, I wrote a function that does the opposite of your function, i.e. megres clock lines. See https://gist.github.com/heikkil/76e8fbae3fbf6599870e6c0ca1f3c62b

If you want to combine these two into a MELPA package, that would be great. They complement each other nicely.

### PR DESCRIPTION
**Pull request by miguelmorin**
This PR separates the reading and writing from the org buffer from the processing of timestamps. The advantages are:
- string processing functions can have tests that increase reliability and ensure backwards compatibility
- new features are easier to add, such as providing the duration of the end segment instead of the initial segment, or splitting by a time of day

Closes #6.

### CODE REVIEW

**Comment by justintaft** [comment]
Thanks for the PR, will review tomorrow.

**Comment by justintaft** [comment]
Can you please modify the code to recognize and preserve whitespace? Splitting the following clock entry fails, due to whitespace not being recognized.

```
* Test 2
  :LOGBOOK:
  CLOCK: [2019-12-14 Sat 23:51]--[2019-12-15 Sun 00:51] =>  1:00
  :END:
```

The PR looks good otherwise, thank you.

**Comment by justintaft** [comment]
I performed a manual merge. Thank you for the PR.

**Comment by miguelmorin** [comment]
Sorry, I've been away from email. My org mode doesn't include whitespace before `CLOCK:`, does yours or did you customize the `org-clock-string` variable? From the test you added, it seems that the code won't work in my Org mode.

**Comment by justintaft** [comment]
@miguelmorin I'll look in to this tonight and will try with vanilla emacs setup. 

Below is an example org content when I clocked in. I split the entry with and without whitespace before `CLOCK` with `org-clock-split``, and both produced the correct results for me. 

```
* Test
  :LOGBOOK:
  CLOCK: [2019-12-18 Wed 14:06]--[2019-12-18 Wed 14:08] =>  0:02
  :END:

hello world
```

Following is help for the variable `org-clock-string`

```
org-clock-string is a variable defined in ‘org.el’.
Its value is "CLOCK:"
```

**Comment by justintaft** [comment]
Also please note as `defvar` is being used, it  won’t update if you have already defined it. 

An emacs restart or using `setq` to set the new value may be required.

**Comment by alphapapa** [comment]
> Also please note as `defvar` is being used, it won’t update if you have already defined it. An emacs restart or using `setq` to set the new value may be required.

You can use `C-M-x` to force `defvar`s to be re-evaluated.

**Comment by justintaft** [comment]
@miguelmorin I added a simple system test to check splitting. It appears to be working fine with and without whitespace before "CLOCK". Please see my above comment on `defvar` and see if it fixes the issue.

**Comment by miguelmorin** [comment]
You're right, the `defvar` doesn't update. It should still have worked either with my previous definition or with yours. I'm not sure what happened and I can't remember it now. I'll report if I find it.

I like the system test you added with the buffer and the split!

**Pull request closed without merging**
